server:
  port: 8092

management:
  security:
    enabled: false
kafka:
  topic: weather
  bootstrapServers: kafka:9092
  consumerGroup: local

app:
  dasWeatherServiceId: localhost
  dasWeatherServicePort: 8092
  saveResponse: /api/v1/weatherAudit
  getHistoric: /api/v1/weatherAudit/city({city}/prediction/{prediction}
